#Database config
spring:
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create-customer.sql
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/db_ec_customer_local
    username: postgres
    password: 62312898
