spring:
  application:
    name: ec-seller
  config:
    import: "configserver:"
  profiles:
    active: test
#Server config
server:
  port: 8080
#Eureka config
eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

