spring:
  application:
    name: ec-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ec-product
          uri: lb://ec-product
          predicates:
            - Path=/product/**
        - id: ec-customer
          uri: lb://ec-customer
          predicates:
            - Path=/customer/**
        - id: ec-seller
          uri: lb://ec-seller
          predicates:
            - Path=/seller/**
        - id: ec-shopping-cart
          uri: lb://ec-shopping-cart
          predicates:
            - Path=/order/**
        - id: ec-oauth
          uri: lb://ec-oauth
          predicates:
            - Path=/oauth/**
        - id: ec-email
          uri: lb://ec-email
          predicates:
            - Path=/email/**
          ouath:
            sensitive-headers: Cookie,Set-Cookie
#Server config
server:
  port: 7000
#Eureka client
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
